# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 22:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uc_links', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='uc_links.Person'),
        ),
    ]
