# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 20:28
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uc_links', '0007_auto_20170920_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Text symbols and -, without digits', regex='^[^\\W\\d_]+(-[^\\W\\d_]+)?$')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Text symbols and -, without digits', regex='^[^\\W\\d_]+(-[^\\W\\d_]+)?$')]),
        ),
    ]
